version: 0.1.{build}

image: Visual Studio 2017

configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
  
build:
  project: .\Giver.sln
  verbosity: minimal
  
before_build:
  - dotnet restore

after_build:
- dotnet pack Giver\Giver.csproj -c Release /p:Version=%appveyor_build_version%
- appveyor PushArtifact Giver\bin\Release\Giver.%appveyor_build_version%.nupkg

test_script:
- dotnet test -c %CONFIGURATION% Giver.Tests\Giver.Tests.csproj
- nuget install OpenCover -Version 4.6.519 -OutputDirectory tools
- .\tools\OpenCover.4.6.519\tools\OpenCover.Console.exe -target:"c:\Program Files\dotnet\dotnet.exe" -targetargs:"test -f netcoreapp1.1 -c %CONFIGURATION% Giver.Tests/Giver.Tests.csproj" -filter:"+[Giver*]* -[Giver.*Tests*]*" -output:opencoverCoverage.xml -oldStyle -register:user
- nuget install coveralls.net -Version 0.7.0 -OutputDirectory tools
- .\tools\coveralls.net.0.7.0\tools\csmacnz.Coveralls.exe --opencover -i opencoverCoverage.xml --repoToken "%COVERALLS_REPO_TOKEN%" --useRelativePaths --commitId "%APPVEYOR_REPO_COMMIT%" --commitBranch "%APPVEYOR_REPO_BRANCH%" --commitAuthor "%APPVEYOR_REPO_COMMIT_AUTHOR%" --commitEmail "%APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL%" --commitMessage "%APPVEYOR_REPO_COMMIT_MESSAGE%" --jobId "%APPVEYOR_BUILD_NUMBER%" --serviceName appveyor

artifacts:
- path: '**\*.nupkg'
  name: NuGet

deploy:
  provider: NuGet
  api_key:
    secure: hQY0HMU8ADJvqFfivG/Z0+h2Nz8xFCFd64ERHhaTFc3SzRy3Kz8C3FE8tiJMqMjz
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    appveyor_repo_tag: true
